spring.datasource.oracle.jdbc-url=jdbc:oracle:thin:@//HOST:PORT/SERVICE
spring.datasource.oracle.username=ORACLE_USER
spring.datasource.oracle.password=ORACLE_PASSWORD
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/dbname
spring.datasource.mysql.username=MYSQL_USER
spring.datasource.mysql.password=MYSQL_PASSWORD
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

spring.batch.initialize-schema=always
